// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4qEkc6uQek8GA1EwOtiZSTPyNGoYybg',
    appId: '1:125047896914:web:5a50a7916beb283a4fd88b',
    messagingSenderId: '125047896914',
    projectId: 'options-trainer',
    authDomain: 'options-trainer.firebaseapp.com',
    storageBucket: 'options-trainer.firebasestorage.app',
    measurementId: 'G-FJ89F0PGT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxAqUWUG9-NCEVMVejs0tOWyy7noPxBjs',
    appId: '1:125047896914:android:0d83e18335abdb3b4fd88b',
    messagingSenderId: '125047896914',
    projectId: 'options-trainer',
    storageBucket: 'options-trainer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuNLSYeJeUd2Fzlbkhn0aCpprznsar154',
    appId: '1:125047896914:ios:e94d85593f9d02584fd88b',
    messagingSenderId: '125047896914',
    projectId: 'options-trainer',
    storageBucket: 'options-trainer.firebasestorage.app',
    iosBundleId: 'com.example.paperTrading',
  );
}
